spring:
  application:
    name: bookingservice
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb1
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9092
