server:
  port: 5555

spring:
  application:
    name: apigateway

  cloud:
    discovery:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTHSERVICE
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /${segment}

            - id: microservice-api-1
              uri: lb://MICROSERVICE-1
              predicates:
                - Path=/micro1/**
              filters:
                - RewritePath=/micro1/(?<segment>.*), /${segment}

            - id: propertyservice-api
              uri: lb://PROPERTYSERVICE
              predicates:
                - Path=/property/**
              filters:
                - RewritePath=/property/(?<segment>.*), /${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
